// ========================================
// App Module - Main Controller
// ========================================
const App = {
  currentPage: 'dashboard',

  async init() {
    await this.autoConnectKeys();
    this.seedDefaultTasks();
    this.bindNavigation();
    Chatbot.init();
    Calendar.init();
    Dashboard.init();
    ContentBoard.init();
    Instagram.init();
    TeamSync.init();
    ContentAgent.init();
    if (typeof UploadPlanner !== 'undefined') UploadPlanner.init();

    // Check URL hash or default to ai-agent
    const hash = window.location.hash.slice(1);
    if (typeof BlogWP !== 'undefined') BlogWP.init();
    if (['chatbot','calendar','dashboard','content-board','instagram','competitors','ads','ai-agent','ai-agent-new','blog-wp'].includes(hash)) {
      this.switchPage(hash);
    } else {
      this.switchPage('dashboard');
    }

    // Set today's date as default for stat input
    const dateInput = document.getElementById('stat-date');
    if (dateInput) dateInput.value = Storage.formatDate(new Date());

    // 채널 데이터 자동 로딩 (백그라운드)
    setTimeout(() => {
      this.autoFetchChannelData();
      this.autoFetchInstagram();
    }, 800);
  },

  async autoConnectKeys() {
    try {
      const res = await fetch('/api/config');
      if (!res.ok) return;
      const cfg = await res.json();
      if (cfg.youtube && cfg.youtube.apiKey) {
        localStorage.setItem('yt_api_key', cfg.youtube.apiKey);
      }
      if (cfg.instagram && cfg.instagram.token) {
        localStorage.setItem('ig_token', cfg.instagram.token);
        if (cfg.instagram.userId) localStorage.setItem('ig_user_id', cfg.instagram.userId);
      }
    } catch (e) {
      console.warn('자동 연결 실패:', e.message);
    }
  },

  async autoFetchChannelData() {
    if (typeof ContentBoard === 'undefined' || typeof YouTubeService === 'undefined') return;
    const channels = ['bilsanam', 'seoulspace'];
    for (const key of channels) {
      const ch = ContentBoard.CHANNELS[key];
      if (!ch) continue;
      try {
        let cached = null;
        try { cached = JSON.parse(localStorage.getItem(ch.cacheKey)); } catch {}
        if (cached) {
          const data = cached.data || cached;
          const ts = cached.timestamp || (cached.fetchedAt ? new Date(cached.fetchedAt).getTime() : 0);
          if (data && data.channelInfo && (Date.now() - ts) < 6 * 60 * 60 * 1000) continue;
        }

        YouTubeService.CACHE_KEY = ch.cacheKey;
        let channelId = localStorage.getItem(ch.channelIdKey);
        if (!channelId) {
          const found = await YouTubeService.searchChannel(ch.search);
          if (found && found[0]) {
            channelId = found[0].id;
            localStorage.setItem(ch.channelIdKey, channelId);
          }
        }
        if (channelId) {
          YouTubeService.setChannelId(channelId);
          const result = await YouTubeService.getRecentVideos(30);
          const data = { channelInfo: result.channelInfo, videos: result.videos };
          YouTubeService.saveCache(data);
        }
      } catch (e) {
        console.warn(`${key} 자동 연결 실패:`, e.message);
      }
    }
    if (this.currentPage === 'dashboard' && typeof Dashboard !== 'undefined') Dashboard.refresh();
  },

  async autoFetchInstagram() {
    if (typeof Instagram === 'undefined' || !Instagram.fetchData) return;
    try {
      let cached = null;
      try { cached = JSON.parse(localStorage.getItem('ig_cache')); } catch {}
      if (cached) {
        const data = cached.data || cached;
        const ts = cached.timestamp || 0;
        if (data && data.profile && (Date.now() - ts) < 6 * 60 * 60 * 1000) return;
      }
      await Instagram.fetchData(true);
    } catch (e) {
      console.warn('인스타그램 자동 연결 실패:', e.message);
    }
    if (this.currentPage === 'dashboard' && typeof Dashboard !== 'undefined') Dashboard.refresh();
  },

  seedDefaultTasks() {
    if (localStorage.getItem('ct_seeded_20260518') === '1') return;
    const seeds = [
      { date: '2026-05-18', text: '[업로드 - 빌사남] 성수 서연무장길 2편 / 양승주PD', category: '유튜브', categoryEmoji: '🎬' },
      { date: '2026-05-21', text: '[업로드 - 빌사남] 재활병원 임차인 / 배미진 PD', category: '유튜브', categoryEmoji: '🎬' }
    ];
    seeds.forEach(s => Storage.addTask(s));
    localStorage.setItem('ct_seeded_20260518', '1');
  },

  async autoGenerateDaily() {
    // 오늘 이미 생성했는지 확인
    const today = Storage.formatDate(new Date());
    const lastRun = localStorage.getItem('ct_agent_last_auto');
    if (lastRun === today) return;

    // API 키 확인
    if (!ContentAgent.getApiKey()) return;

    // 약간의 딜레이 후 자동 실행
    setTimeout(async () => {
      try {
        localStorage.setItem('ct_agent_last_auto', today);
        await ContentAgent.fetchNews();
        await ContentAgent.getRecommendations();
      } catch (e) {
        console.error('자동 콘텐츠 생성 오류:', e);
      }
    }, 1500);
  },

  bindNavigation() {
    document.querySelectorAll('.nav-item').forEach(item => {
      item.addEventListener('click', () => {
        this.switchPage(item.dataset.page);
      });
    });
  },

  switchPage(page) {
    this.currentPage = page;
    window.location.hash = page;

    document.querySelectorAll('.nav-item').forEach(item => {
      item.classList.toggle('active', item.dataset.page === page);
    });

    document.querySelectorAll('.page').forEach(p => {
      p.classList.toggle('active', p.id === `${page}-page`);
    });

    if (page === 'calendar') { Calendar.refresh(); Chatbot.scrollToBottom(); if (typeof UploadPlanner !== 'undefined') UploadPlanner.render(); }
    if (page === 'dashboard') Dashboard.refresh();
    if (page === 'content-board') ContentBoard.refresh();
    if (page === 'instagram') Instagram.refresh();
    if (page === 'chatbot') Chatbot.scrollToBottom();
    if (['leads','competitors','ads'].includes(page)) Marketing.refreshPage(page);
    if (page === 'ai-agent') ContentAgent.init();
    if (page === 'blog-wp' && typeof BlogWP !== 'undefined') BlogWP.refresh();
  }
};

document.addEventListener('DOMContentLoaded', () => App.init());
