// ========================================
// App Module - Main Controller
// ========================================
const App = {
  currentPage: 'ai-agent',

  init() {
    this.bindNavigation();
    Chatbot.init();
    Calendar.init();
    Dashboard.init();
    ContentBoard.init();
    Instagram.init();
    TeamSync.init();
    ContentAgent.init();

    // Check URL hash or default to ai-agent
    const hash = window.location.hash.slice(1);
    if (['chatbot','calendar','dashboard','content-board','instagram','competitors','ads','ai-agent'].includes(hash)) {
      this.switchPage(hash);
    } else {
      this.switchPage('ai-agent');
    }

    // Set today's date as default for stat input
    const dateInput = document.getElementById('stat-date');
    if (dateInput) dateInput.value = Storage.formatDate(new Date());

    // 자동으로 오늘의 콘텐츠 생성 시작
    this.autoGenerateDaily();
  },

  async autoGenerateDaily() {
    // 오늘 이미 생성했는지 확인
    const today = Storage.formatDate(new Date());
    const lastRun = localStorage.getItem('ct_agent_last_auto');
    if (lastRun === today) return;

    // API 키 확인
    if (!ContentAgent.getApiKey()) return;

    // 약간의 딜레이 후 자동 실행
    setTimeout(async () => {
      try {
        localStorage.setItem('ct_agent_last_auto', today);
        await ContentAgent.fetchNews();
        await ContentAgent.getRecommendations();
      } catch (e) {
        console.error('자동 콘텐츠 생성 오류:', e);
      }
    }, 1500);
  },

  bindNavigation() {
    document.querySelectorAll('.nav-item').forEach(item => {
      item.addEventListener('click', () => {
        this.switchPage(item.dataset.page);
      });
    });
  },

  switchPage(page) {
    this.currentPage = page;
    window.location.hash = page;

    document.querySelectorAll('.nav-item').forEach(item => {
      item.classList.toggle('active', item.dataset.page === page);
    });

    document.querySelectorAll('.page').forEach(p => {
      p.classList.toggle('active', p.id === `${page}-page`);
    });

    if (page === 'calendar') { Calendar.refresh(); Chatbot.scrollToBottom(); }
    if (page === 'dashboard') Dashboard.refresh();
    if (page === 'content-board') ContentBoard.refresh();
    if (page === 'instagram') Instagram.refresh();
    if (page === 'chatbot') Chatbot.scrollToBottom();
    if (['leads','competitors','ads'].includes(page)) Marketing.refreshPage(page);
    if (page === 'ai-agent') ContentAgent.init();
  }
};

document.addEventListener('DOMContentLoaded', () => App.init());
